### ISSUE TITLE
v107 code getting restClient.RestClientOptions throws Exception 'System.NullReferenceException'

### ISSUE THREAD

**Issue by hemant-karwade** [yuessir/RestSharpPolly#11]
`
           
        var policy = BuildTimeoutAndRetryPolicy2(3, 1, 60);
        IRestClient<RestResponse> restClient = new RestClientFactory<RestResponse>().Create(policy);
        Uri uri = new Uri("http://localhost:5000");
        Console.WriteLine("Host:"+uri.Host);
        restClient.RestClientOptions.BaseUrl = new Uri("http://localhost:5000");
        return restClient.Build(restClient.RestClientOptions);
`

I have tried above code, but getting "**Exception thrown: 'System.NullReferenceException' in dotnet-helloworld.dll**" on "**restClient.RestClientOptions.BaseUrl = new Uri("http://localhost:5000");**"

Any idea why **RestClientOptions** is coming as null
![image](https://user-images.githubusercontent.com/53491176/176605973-49332848-b2ea-426a-808f-29301f67fe9a.png)

Following package version being used

DotNet: 5.0
restsharp:  107.3.0
Polly: 7.2.2

**Comment by yuessir** [comment]
44c26c9d8460f50f0696fe93275146a1aa1aedab

**Comment by hemant-karwade** [comment]
thanks @yuessir for quick fix

**Comment by yuessir** [comment]
> thanks @yuessir for quick fix

if you like the project, you can star it.
