### ISSUE TITLE
IRestSharp Interface implementation errors

### ISSUE THREAD

**Issue by andymiddleditch** [yuessir/RestSharpPolly#2]
Getting the following build error on this....	

	Message	"Method 'Execute' on type 'RestSharpPolly.RestClientFactory`1' from assembly 'RestSharpPolly, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' tried to implicitly implement an interface method with weaker type parameter constraints."	string

Any ideas?

**Comment by m1dst** [comment]
It seems it is built against RestSharp 106.5.4 and the interfaces started to change after that point.  There have been 13 RestSharp releases since this was built.  Not sure how much requires changing but I'm going to spend a few minutes now seeing if I can get it to compile.

**Comment by yuessir** [comment]
Hi @andymiddleditch 
You can import RestSharpPolly  into an existing project by installing the Nuget package reference.
    `$ dotnet add package RestSharpPolly`
@m1dst  Thanks, please let me know if you have the same issues.

**Comment by m1dst** [comment]
Your project compiles for me without changes.  I assume the NuGet should be fine.  I think this might be to do with the RestSharp version.  I have sent a pull request which I'd like you to review to bring it up to date with the latest RestSharp version.
