### ISSUE TITLE
Suggestion: why not target netstandard 2.0?

### ISSUE THREAD

**Issue by quicoli** [yuessir/RestSharpPolly#4]

**Comment by yuessir** [comment]
@quicoli Thanks for the suggestion. I will do that and plann capabilities. :)

**Comment by yuessir** [comment]
see 467b1eaa563f250a78692b0fd40203045a592e6b

https://github.com/yuessir/RestSharpPolly/commit/467b1eaa563f250a78692b0fd40203045a592e6b#r50150829
