### ISSUE TITLE
Not getting any output in console App run or Unit Tests. 

### ISSUE THREAD

**Issue by jeffjmc** [yuessir/RestSharpPolly#5]
Thanks so much for contributing this.  I think it is exactly what I need.     I am trying to confirm everything is working. I believe I should be getting console output messages that confirm that the operation has been re-attempted?   When I run the console app there is no output.   the system does progress and exit after consuming the three Console.ReadKey() calls however.  

right now I am testing this as built.  but I hope to get it running with .Net Framework 4.5.2.  any advice?

**Comment by yuessir** [comment]
@jeffjmc  thanks, see the latest commit with unit test.

**Comment by yuessir** [comment]
Hi, if you have any problems,feel free to open another issue.
