### ISSUE TITLE
Any way to get this project built targeting the .Net Standard framework so it is compatible with .Net Full and .Net Core?

### ISSUE THREAD

**Issue by CDiverChris** [yuessir/RestSharpPolly#6]
Could give greater compatibility if targeting the .Net Standard framework.

**Comment by CDiverChris** [comment]
Checking between the target frameworks of both RestSharp and Polly, I think you'll get the best compatibility if you do the following: 

  <PropertyGroup>
	  <TargetFrameworks>net461;net472;netstandard2.0;</TargetFrameworks>
  </PropertyGroup>

**Comment by yuessir** [comment]
https://github.com/yuessir/RestSharpPolly/commit/a9595117ca92923fff643841c4e9609b7777b440#diff-b5b06003811a0ea43b516b5f65cd92218633a0e45aa8597bca1e7339171c6344R4
