### ISSUE TITLE
Support for RestSharp v 107

### ISSUE THREAD

**Issue by matejgolob** [yuessir/RestSharpPolly#7]
Any plans to upgrade library for supporting RestSharp V107 (removed IRestClient/IRestReponse interfaces...)?
https://restsharp.dev/v107/#restsharp-v107

**Comment by Pureaznangel** [comment]
Thanks for requesting. I am still facing the same issue.

**Comment by yuessir** [comment]
> Any plans to upgrade library for supporting RestSharp V107 (removed IRestClient/IRestReponse interfaces...)? https://restsharp.dev/v107/#restsharp-v107

Yeah... Later i will refactor code and release  a new version.

**Comment by BigHoss** [comment]
Any progress on that?

**Comment by yuessir** [comment]
@BigHoss  hi ,checkout the branch **`V107`**

in the v107 case,

```  var asyncPolicy2 = BuildTimeoutAndRetryAsyncPolicy2(3, 2, 10);
            var client1 = new RestClientFactory<RestResponse>().Create(asyncPolicy2);
            var request1 = new RestRequest();
            
            client1.RestClientOptions.BaseUrl = new Uri("https://httpstat.us/500");
            var host = client1.Build(client1.RestClientOptions);
            var response5 = await host.ExecuteAsync(request1);
            Console.ReadKey();
```

under v107 ( see reademe)

 ```
var client = RestClientFactory<IRestResponse>.Create(TimeoutAndRetryPolicy.Build(3, 10, 60));
            client.BaseUrl = new Uri("");
            var request = new RestRequest(Method.GET);
            request.AddJsonBody(model);
            var response = client.Execute(request);
```
            
**NOT fully tested, Not recommended for  production use unless you know what you're doing. :)**
btw official RestSharp 107.3.0 is not compatible with .net45 /.net46 /.net47, so [RestSharpPolly](https://github.com/yuessir/RestSharpPolly) does not support for the frameworks.

**Comment by yuessir** [comment]
If the v107 branch has some problems for your test case, you could be able to open the new issue.

**Comment by BigHoss** [comment]
@yuessir what i dont understand is why are you still supporting frameworks that are deprecated for that long of a time. just throw them out, all the people still using them should be locked into old versions, not people using current tech
